[project]
name = "trader"
version = "0.1.0"
description = "AI pilled automated trading system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ibapi @ file:///${PROJECT_ROOT}/twsapi/IBJts/source/pythonclient",
]
